## Numpy

numpy liberary is use for working with arrays 

NumPy stands for Numerical Python

## Why Use Numpy

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.


## Why is Nympy faster than list

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

**List** :- Each item is stored in a separate memory location

**Arrays** :- All items are stored in one continuous block of memory

## Install numpy 

**pip install numpy**

Chek the version of numpy

In [7]:
import numpy as np

print(np.__version__)

2.3.0


In [ ]:
arr = np.array((1,2,3,4,5))
print(arr)
print()
print(type(arr)) 

[1 2 3 4 5]

<class 'numpy.ndarray'>


## Access Array Element

In [ ]:
import numpy as np
arr = np.array([40,"element",22,"elementry"])
print(arr[2])

22


In [ ]:
import numpy as np
arr = np.array([2,4,6,8,10])
print(arr[1]+arr[2]) # add 4 and 6

10


In [26]:
import numpy as np
arr = np.array([1,2,3,4,5,6])

print(arr[1:5]) # index start from 0 
print()
print(arr[:4])
print()
print(arr[:-1])
print()
print(arr[::-1]) # negative indexing
print()
print(arr[0:6:2]) # access item by 1 step
print()
print(arr[::-2])

[2 3 4 5]

[1 2 3 4]

[1 2 3 4 5]

[6 5 4 3 2 1]

[1 3 5]

[6 4 2]


## Slicing 2D-Array

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]]) # 2d array on 0 or 1 position
print(arr[1,2:4]) #access element 1 index array
print()
print(arr[0:2,2]) # from 0 to 1 array get the 2 element of both array
print()
print(arr[0:3,2:4]) #get second and third element from 0 to 2 arrays

[8 9]

[3 8]

[[3 4]
 [8 9]]


## array works with different data types

In [40]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [42]:
import numpy as np

arr = np.array(["length", "of", "string", "different"])

print(arr.dtype)

<U9


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4] , dtype = "S") # convert to string data type
print(arr)

print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


## Converting Data Type on Existing Arrays

The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter




In [46]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])
print(arr.dtype)

newarr = arr.astype('i')
print()
print(newarr)
print(newarr.dtype)

float64

[1 2 3]
int32


## Change data type from integer to boolean

In [52]:
import numpy as np

arr = np.array([1.6, 0., 0.7,0])
print(arr.dtype)
print()
newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

float64

[ True False  True False]
bool


In [65]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## Array of zeros and ones

In [21]:
import numpy as np
zeros_array = np.zeros((2,3))
print(zeros_array)

print()
ones_array = np.ones((3,5),dtype = "int")
print(ones_array)

[[0. 0. 0.]
 [0. 0. 0.]]

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## np.arange()

In [20]:
import numpy as np
a = np.arange(12)
print(a)
print()

b = np.arange(start = 5,stop = 30,step = 2)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[ 5  7  9 11 13 15 17 19 21 23 25 27 29]



## Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10.
**Hint: Use np.arange() and reshape() function.**

In [47]:
import numpy as np
arr = np.arange(100,200,10).reshape(5,2)
print(arr)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


## Following is the provided numPy array. Return array of items by taking the third column from all rows.
**sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])**

In [62]:
import numpy as np
arr = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
print(arr)
arr[:,-1]


[[11 22 33]
 [44 55 66]
 [77 88 99]]


array([33, 66, 99])

## Basic operation of an array 

### Arithmetic Operation 

In [67]:
# add,subtract,multiply or divide 
import numpy as np
array1  = np.array([[2,3,5,7],[1,4,6,8]])
array2 = np.array([[2,3,4,5],[4,5,6,7]])
print(array1+array2)
array1/array2

[[ 4  6  9 12]
 [ 5  9 12 15]]


array([[1.        , 1.        , 1.25      , 1.4       ],
       [0.25      , 0.8       , 1.        , 1.14285714]])

In [69]:
#Multiplication of Two matrix
import numpy as np
arr1 = np.array([[3, 6, 7], [5, -3, 0]])
arr2 = np.array([[1, 1], [2, 1], [3, -3]])
arr1.dot(arr2)

array([[ 36, -12],
       [ -1,   2]])

## Comparison operation 

In [68]:
import numpy as np

arr = np.array([5, 10, 15, 20])
greater_than = arr>10
less_than = arr<15
equals_to = arr==5

#print result
print("Original Array: ",arr)
print("Elements greater than 10: ",greater_than)
print("Elements less than 15: ",less_than)
print("Elements Equals to 5",equals_to)

Original Array:  [ 5 10 15 20]
Elements greater than 10:  [False False  True  True]
Elements less than 15:  [ True  True False False]
Elements Equals to 5 [ True False False False]


## reshape array

In [77]:
# Turn a 1D array of 6 items into a 2D array with 2 rows and 3 columns.
import numpy as np

arr = np.array([5, 10, 15, 20,30,22])
newarray = np.reshape(arr,(2,3))
print(newarray)
print(newarray.flatten().ndim)

[[ 5 10 15]
 [20 30 22]]
1


In [81]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
